# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
trigger:
- main
pool:
  vmImage: ubuntu-latest
steps:
- task: MavenAuthenticate@0
  displayName: 'Maven Authenticate'
  inputs:
    artifactsFeeds: MSP  
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
   # testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/s/target'
    publishLocation: 'pipeline'
    artifactName: 'MSPBackend.jar'
  # -bash: |
  # sudo apt install -y awscli
  # aws configure set aws_access_key_id $(ACCESS_KEY); aws configure set aws_secret_access_key $(SECRET_ACCESS_KEY); aws configure set default.region ap-south-1
  # mv '$(Pipeline.Workspace)'/s/target/MSPBackend.jar '$(Pipeline.Workspace)'/s/target/MSPBackend.jar_`date +"%Y-%m-%d-%H-%M"`
  # ls -al '$(Pipeline.Workspace)'/s/target/
  # aws s3 cp '$(Pipeline.Workspace)'/s/target/MSPBackend.jar_* s3://ilantus-build-artifacts/build/MSP-$(Build.SourceBranchName)/
  # rm -rf ~/.aws
